version: "3.9"
services:
  app:
    build: .
    container_name: noteapp
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
     - db
  db:
    image: mariadb:latest
    restart: always
    container_name: noteapidb
    environment:
      - MYSQL_DATABASE:noteapidb
      - MYSQL_USER=svengates
      - MYSQL_PASSWORD=hackme123
      - MYSQL_ROOT_PASSWORD=hackme123
      - MYSQL_HOST=localhost
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db_data:

  # sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver